#!/bin/bash

# honeywell-dpl-drv 
#
# CUPS filter wrapper script, converting incoming PDF stream to Datamax
# DPL.
#
# Copyright (C) 2012 Intermec Technologies Pte Ltd
#

# Debug log during development
echo "honeywell-dpl-drv: ${@}" | logger

# Base path for temporary files
TMPBASEPATH="/tmp/honeywell-dpl-drv-$$"

# delete_temp_files() deletes all temporary files used for printing conversion
delete_temp_files()
{
  rm -f ${TMPBASEPATH}*
}

# exit_with_error() prints out troubleshooting message in actual print job
exit_with_error()
{
  echo "Printing not complete" >> ${TMPBASEPATH}.log 
 
  #Print DPL label with containing error msg
  echo -e "\02L"
  echo "D11"
  echo "n"
  echo "IV+"
  echo "3911S0100800180P014P014ERROR: ${ERRMSG}"
  echo "Q0001"
  echo "E"

  # Delete temporary files
  delete_temp_files

  exit 1;
}

# Input data in PS or PDF format
cat <&0 > ${TMPBASEPATH}.in

# Check input data and convert from PS if needed
head -1 ${TMPBASEPATH}.in | grep PDF > /dev/null
ISPDF="$?"
head -1 ${TMPBASEPATH}.in | grep PS > /dev/null
ISPS="$?"

if [ ${ISPS} = "0" ]; then
  # Convert PS data to PDF
  ps2pdf ${TMPBASEPATH}.in - > ${TMPBASEPATH}.pdf
else 
  if [ ${ISPDF} != "0" ]; then
    logger "neither PDF nor PS data provided to driver, exiting"
    # Delete temporary files
    delete_temp_files
    exit 1;
  else
    # Input data PDF is simply passed on
    cp ${TMPBASEPATH}.in ${TMPBASEPATH}.pdf
  fi
fi


# Configure printer settings

# Set default values
resolution=203
dithering=0.5
colormode=gray
foundcopy=0
collate=no

# Loop through arguments
for ARG in ${@} ;
do
  param=`echo ${ARG} | cut -f 1 -d '='`
  value=`echo ${ARG} | cut -f 2 -d '='`

  if [ ${value} != ${param} ]; then
    if [ ${foundcopy} = 0 ]; then
      COPIES=${tmpcopies}
      let foundcopy=1
    fi
  fi

  case "${param}" in
    Collate)
      case "${value}" in
        Collate)
          logger "Set Collate Mode"
          collate=yes
          ;;
        *)
          logger "Don't set collate"
          ;;
      esac
      ;;
    PageSize)
      logger "2 = ${param} - ${value}"
        
      ;;

    inPrintSpeed)
      case "${value}" in
        1)
          logger "Set Print Speed 1"
          #echo -e "\02KcpSA"
          ;;
        1.5)
          logger "Set Print Speed 1.5"
          #echo -e "\02KcpSB"
          ;;
        2)
          logger "Set Print Speed 2"
          #echo -e "\02KcpSC"
          ;;
        2.5)
          logger "Set Print Speed 2.5"
          #echo -e "\02KcpSD"
          ;;
        3)
          logger "Set Print Speed 3"
          #echo -e "\02KcpSE"
          ;;
        3.5)
          logger "Set Print Speed 3.5"
          #echo -e "\02KcpSF"
          ;;
        4)
          logger "Set Print Speed 4"
          #echo -e "\02KcpSG"
          ;;
        4.5)
          logger "Set Print Speed 4.5"
          #echo -e "\02KcpSH"
          ;;
        5)
          logger "Set Print Speed 5"
          #echo -e "\02KcpSI"
          ;;
        *)
          logger "Dont change print speed"
          ;;
      esac
      ;;

      inMediaType)
        case "${value}" in
          Gap)
            logger "Set Label With Gaps"
            #echo -e "\02KcSTG"
            ;;
          MarkBot)
            logger "Set Black Mark Bottom"
            #echo -e "\02KcSTR"
            ;;
          MarkTop)
            logger "Set Black Mark Top"
            #echo -e "\02KcSTT"
            ;;
          Cont)
            logger "Set Continuous"
            #echo -e "\02KcSTC"
            ;;
          *)
            logger "Dont change media type"
            ;;
        esac
        ;;

      inDarkness)
        logger "Set Darkness to ${value}"
        #echo -e "\02KcHE${value}"
        ;;

      inColormode)
        logger "Set Color to ${value}"
        colormode="${value}"
        ;;

      inResolution)
        case "${value}" in
          203dpi)
            logger "Set Resolution to ${value}"
            resolution=203
            ;;
          300dpi)
            logger "Set Resolution to ${value}"
            resolution=300
            ;;
          *)
            logger "Default Resolution to ${value}"
            resolution=203
            ;;
        esac
        ;;

      *)
        logger "Ignore: ${param} - ${value}"
        
        # The last argument before first attribute is the copies
        tmpcopies=${param}  
        ;;
    esac
  done

  # Set Media Size based on Resolution
  case "${resolution}" in 
    203)
      ;;

    300)
      ;;

    *)
      ;;
  esac

# Make sure the value of COPIES is a number
if ! [[ ${COPIES} =~ ^[0-9]+$ ]]; then
  COPIES=1
fi

logger "Copies: ${COPIES}"

# Everything in this world is not logical
if [ "${colormode}" = "bw" ]; then
  # Convert PDF to PGM using pdftoppm (black and white)
  pdftoppm -r ${resolution} -gray ${TMPBASEPATH}.pdf ${TMPBASEPATH}-pgm >> \
  ${TMPBASEPATH}.log 2>> ${TMPBASEPATH}.log
else
  # Convert PDF to PBM using pdftoppm (gray scale)
  pdftoppm -r ${resolution} -mono ${TMPBASEPATH}.pdf ${TMPBASEPATH}-pbm >> \
  ${TMPBASEPATH}.log 2>> ${TMPBASEPATH}.log
fi

# Check and remove zero padding PGM filenames
PAGENO=1
if [ ! -f "${TMPBASEPATH}-pgm-${PAGENO}.pgm" ]; then
  for f in ${TMPBASEPATH}-pgm*.pgm 
  do 
    mv $f ${TMPBASEPATH}-pgm-${PAGENO}.pgm
    logger "Copy $f ${TMPBASEPATH}-pgm-${PAGENO}.pgm"
    let PAGENO=${PAGENO}+1
  done
fi

# Convert PGM to PBM using pgmtopbm
PAGENO=1
while [ 1 ]
do
  # Check if PBM file exists
  if [ -f "${TMPBASEPATH}-pgm-${PAGENO}.pgm" ]; then

    pgmtopbm -threshold -value ${dithering} ${TMPBASEPATH}-pgm-${PAGENO}.pgm \
      > ${TMPBASEPATH}-pbm-${PAGENO}.pbm 2>> ${TMPBASEPATH}.log

    logger "${dithering}"
    logger "pgmtopbm -threshold -value ${dithering} ${TMPBASEPATH}-pgm-${PAGENO}.pgm  > ${TMPBASEPATH}-pbm-${PAGENO}.pbm 2>> ${TMPBASEPATH}.log"
    let PAGENO=${PAGENO}+1
  else
    break;
  fi
done

# XXX: Implement proper return status checking for pdftoppm and pbmtopbm

# Check return status of pdftoppm
RV="$?"
if [ "${RV}" -ne "0" ]; then
  # Interpret exit code
  case "${RV}" in
    0)
    ERRMSG="pdftoppm return (${RV}): No error."
    ;;
    1)
    ERRMSG="pdftoppm return (${RV}): Error opening a PDF file."
    ;;
    2)
    ERRMSG="pdftoppm return (${RV}): Error opening an output file."
    ;;
    3)
    ERRMSG="pdftoppm return (${RV}): Error related to PDF permissions."
    ;;
    99)
    ERRMSG="pdftoppm return (${RV}): Other error."
    ;;
    *)
    ERRMSG="pdftoppm return (${RV}): Unknown error."
    ;;
  esac

  exit_with_error

else
  # Succesfully converted to PBM
  # Check and remove zero padding PBM filenames
  PAGENO=1
  if [ ! -f "${TMPBASEPATH}-pbm-${PAGENO}.pbm" ]; then
    for f in ${TMPBASEPATH}-pbm*.pbm 
    do 
      mv $f ${TMPBASEPATH}-pbm-${PAGENO}.pbm
      let PAGENO=${PAGENO}+1
    done
  fi

  # If not collating then print each page COPIES time
  if [ "${collate}" = "no" ]; then

    PAGENO=1
    while [ 1 ]
    do
      # Check if PBM file exists
      if [ -f "${TMPBASEPATH}-pbm-${PAGENO}.pbm" ]; then

          # Convert PBM to BMP format
          ppmtobmp -windows -bpp=1 < ${TMPBASEPATH}-pbm-${PAGENO}.pbm > ${TMPBASEPATH}-pbm-${PAGENO}.bmp 2>> ${TMPBASEPATH}.log
                      
          # Check return value
          RV="$?"
          if [ "${RV}" -ne "0" ]; then
            ERRMSG="ppmtobmp failed on page ${PAGENO}, exiting."
            exit_with_error
          else
                      
            # Get output data length
            CNT="`wc -c ${TMPBASEPATH}-pbm-${PAGENO}.bmp`"
            LN="`echo ${CNT} | cut -f1 -d' '`"
            logger "BMP size: ${LN}"
            
            #Save image to printer with name IMG1000          
            echo -e "\02IGBIMG1000"
            cat ${TMPBASEPATH}-pbm-${PAGENO}.bmp
            echo ""
            #Need to wait otherwise DO printer will not print
            sleep 1
            echo -e "\02L"
            echo "D11"
            echo "1Y1100000000000IMG1000"
            echo -e "Q${COPIES}\0D"
            echo "E"
         
            # Log progress
            echo "Printed label ${PAGENO}" >> ${TMPBASEPATH}.log 
          fi
      else
        break;
      fi

      # Increment counter, step to next page/label
      let PAGENO=${PAGENO}+1
          
    done
  # Print in collating mode
  else
 
    PAGENO=1
    # Print one full set at a time
    while [ ${COPIES} -ne 0 ]
    do

      # Print each page once
      while [ 1 ]
      do
        # Check if PBM file exists
        if [ -f "${TMPBASEPATH}-pbm-${PAGENO}.pbm" ]; then

            # Convert PBM to BMP format
            ppmtobmp -windows -bpp=1 < ${TMPBASEPATH}-pbm-${PAGENO}.pbm > ${TMPBASEPATH}-pbm-${PAGENO}.bmp 2>> ${TMPBASEPATH}.log      
            
            # Check return value
            RV="$?"
            if [ "${RV}" -ne "0" ]; then
              ERRMSG="ppmtobmp failed on page ${PAGENO}, exiting."
              exit_with_error
            else
                      
              # Get output data length
              CNT="`wc -c ${TMPBASEPATH}-pbm-${PAGENO}.bmp`"
              LN="`echo ${CNT} | cut -f1 -d' '`"
              logger "BMP size: ${LN}"
              
              #Save image to printer with name IMG1000                    
              echo -e "\02IGBIMG1000"
              cat ${TMPBASEPATH}-pbm-${PAGENO}.bmp
              echo ""
              #Need to wait otherwise DO printer will not print
              sleep 1
              echo -e "\02L"
              echo "D11"
              echo "1Y1100000000000IMG1000"
              echo -e "Q${COPIES}\0D"
              echo "E"
              # Log progress
              echo "Printed label ${PAGENO}" >> ${TMPBASEPATH}.log 
            fi
        else
          break;
        fi

        # Increment counter, step to next page/label
        let PAGENO=${PAGENO}+1
        
      done

      let COPIES=${COPIES}-1
    done
  fi

  echo "Printing complete" >> ${TMPBASEPATH}.log

  # Delete temporary files
  delete_temp_files

  # Exit OK
  exit 0;
fi

exit_with_error

